# 控制插件行为的世界列表
worlds:
  - "world"       # 需要管理的世界名（填写 * 表示所有世界）
keepSpawnInMemory: false  # 是否保持出生点区块在内存中

# 自动任务配置
task:
  enabled: true           # 是否启用自动卸载任务
  interval: 15            # 任务间隔（单位：分钟）

# 卸载条件
minPlayersToUnload: 1     # 触发卸载的最小玩家数量（≤此值时卸载）
minChunkActivity: 5       # 区块最小活跃度（低于此值时卸载）

# 垃圾回收配置
garbageCollector:
  task: false             # 是否启用垃圾回收定时任务
  unloading: false        # 是否在卸载区块后执行垃圾回收

# 无玩家时的行为控制
emptyServer:
  unloadAllChunks: true   # 当服务器无玩家时，强制卸载所有非出生点区块
  pauseAutoTask: true     # 当服务器无玩家时，暂停自动任务